### ISSUE TITLE
Nach Löschen einer Transaktion, CD immer noch in Transaktion

### ISSUE THREAD

**Issue by christianb** [christianb/ShareYourMusic#100]
Nachdem ich eine Transaktion gelöscht habe befindet die cd sich noch immer in einer transaktion.

**Comment by happyfaces** [comment]
sollten wir noch dringens beheben, bei mir sind jetzt fast alle cd "in Transaktion", ob wohl keine mehr besteht^^

**Comment by christianb** [comment]
Geht.
