### ISSUE TITLE
CD zweimal in einem modifiziertem Angebot

### ISSUE THREAD

**Issue by christianb** [christianb/ShareYourMusic#103]
Ich habe zwei modifizierte Angebote bekommen.
Darin ist meine CDs zwei mal enthalten. Somit ist meine eigene CD zweimal in einer Transaktion was so nicht sein darf.

**Comment by christian298** [comment]
cds die visible: false oder in_transaction: true sind werden, in der view zum modifizieren, nicht mehr angezeigt
