### ISSUE TITLE
Feedback, Freigeben führt zu verwirrung.

### ISSUE THREAD

**Issue by christianb** [christianb/ShareYourMusic#111]
Feedback
"wenn ich mir die aktivsten benutzer angucke und einen näher betrachten will, sehe ich seine alben/cd's. aber ich kann dann nicht direkt diese cd's zum tausch auswählen :("

**Comment by happyfaces** [comment]
also wenn ich auf 
aktivste Benutzer (sollten wir in "aktivste NUTZER" umbenennen^^)--> dann einen auswähle --> 
sehe ich seine CDs und dort unter jeder CD ist doch ein Tausch button.
Also zum mindestens bei mir

**Comment by christian298** [comment]
cds werden jetzt nach erfolgreichem tausch sofort freigegeben
