### ISSUE TITLE
Gleiche Anfragen löschen (wenn angenommen) wenn selbe CDs enthalten

### ISSUE THREAD

**Issue by christianb** [christianb/ShareYourMusic#87]
Wenn ich ein Angebot bekomme zb:
Meine CD: BoomBox, Geräusch; gegen CD: A Thousand Suns

Und noch ein Angebot: Am Ende Der Sonne, Geräusch; gegen 13

Dann kann ich ja nur ein Angebot annehmen, denn für das andere hab ich ja mindestens eine CD nicht mehr.
Dann sollten doch alle Angebote die nicht mehr erfüllbar sind gelöscht werden, oder?

**Comment by christian298** [comment]
es kann nur ein gleichzeitiges angebot zu einer cd existieren
